version: '3'

services:
  nextjs:
    container_name: cci-web-profile-backoffice
    build:
      context: ./
    image: fe-cci-web-profile-backoffice
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - nextjs-network
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    expose:
      - '3000'
    volumes:
      - ./:/app
      - /app/node_modules 
    command: npm run dev

networks:
  nextjs-network:
    driver: bridge
