version: '3'

services:
  nextjs:
    container_name: cci-web-profile-backoffice
    build:
      context: .
    image: fe-cci-web-profile-backoffice
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - nextjs-network
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  nextjs-network:
    driver: bridge
