name: Deploy CCI staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 \
            --tag kevinirawand/fe-cci-web-profile-backoffice:production \
            -f Dockerfile .
        env:
          NEXT_PUBLIC_OUTPUT: ${{ secrets.STAGING_OUTPUT }}
          NEXT_PUBLIC_HOST: ${{ secrets.NEXT_PUBLIC_HOST }}
          NEXT_PUBLIC_ASSET_PREFIX: ${{ secrets.STAGING_ASSET_PREFIX }}
          NEXT_PUBLIC_BASE_PATH: ${{ secrets.STAGING_BASE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/Web-Profile-Backoffice/
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker system prune -f
